# Generated by Django 4.1.5 on 2023-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('F', 'Familiar'), ('T', 'Trabajo')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
